# Generated by Django 5.2.2 on 2025-08-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('procurer', 'Procurer'), ('client', 'Client')], default='procurer', max_length=10),
        ),
    ]
