# Generated by Django 5.2.2 on 2025-08-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancecheck',
            name='document_scores',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='compliancecheck',
            name='failed_documents',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='compliancecheck',
            name='proposal_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='compliancecheck',
            name='missing_documents',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
