# Generated by Django 5.2.2 on 2025-08-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_compliancecheck_document_scores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancecheck',
            name='document_scores',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='compliancecheck',
            name='failed_documents',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='compliancecheck',
            name='missing_documents',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
