# Generated by Django 5.2.2 on 2025-07-31 14:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='required_documents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, help_text='List of required document types (e.g., CAC, TIN, TAX_CERT, TCC, ISO_PECB)', size=None),
        ),
    ]
