# Generated by Django 5.2.2 on 2025-08-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0002_tender_required_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='extra_documents',
            field=models.FileField(blank=True, null=True, upload_to='tender_extras/'),
        ),
        migrations.AddField(
            model_name='tender',
            name='tender_document',
            field=models.FileField(blank=True, null=True, upload_to='tender_docs/'),
        ),
    ]
