# Generated by Django 5.2.2 on 2025-08-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0003_tender_extra_documents_tender_tender_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='submission_mode',
            field=models.CharField(choices=[('ONE_ENVELOPE', 'Single-stage, one-envelope'), ('TWO_ENVELOPE', 'Single-stage, two-envelope')], default='TWO_ENVELOPE', max_length=20),
        ),
    ]
