# Generated by Django 5.2.2 on 2025-07-02 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='documents',
            new_name='document',
        ),
    ]
