# Generated by Django 5.2.2 on 2025-07-31 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_rename_documents_bid_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='document',
        ),
        migrations.CreateModel(
            name='BidDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(help_text='Type of document (e.g., CAC, TIN, TAX_CERT, TCC, ISO_PECB)', max_length=50)),
                ('file', models.FileField(upload_to='bids/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('extracted_data', models.JSONField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='bids.bid')),
            ],
        ),
    ]
