# Generated by Django 5.2.2 on 2025-07-31 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0003_remove_bid_document_biddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='biddocument',
            name='custom_document_name',
            field=models.CharField(blank=True, help_text="Only required if document_type is 'OTHER'", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='biddocument',
            name='document_type',
            field=models.CharField(choices=[('CAC', 'CAC'), ('TIN', 'TIN'), ('TCC', 'TCC'), ('ISO_PECB', 'ISO PECB'), ('OTHER', 'Other')], help_text="Type of document (e.g., CAC, TIN, etc. Use 'Other' if not listed)", max_length=50),
        ),
    ]
