# Generated by Django 5.2.2 on 2025-08-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0004_biddocument_custom_document_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biddocument',
            name='document_type',
            field=models.CharField(choices=[('BID', 'BID'), ('CAC', 'CAC'), ('TIN', 'TIN'), ('TCC', 'TCC'), ('ISO_PECB', 'ISO PECB'), ('OTHER', 'Other')], help_text="Type of document (e.g., CAC, TIN, etc. Use 'Other' if not listed)", max_length=50),
        ),
    ]
