# Generated by Django 5.2.2 on 2025-08-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0005_alter_biddocument_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='biddocument',
            unique_together={('bid', 'document_type')},
        ),
    ]
