# Generated by Django 5.2.2 on 2025-08-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0006_bid_rank_bid_score_alter_biddocument_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biddocument',
            name='document_type',
            field=models.CharField(choices=[('TECHNICAL_PROPOSAL', 'Technical Proposal'), ('FINANCIAL_PROPOSAL', 'Financial Proposal'), ('CAC', 'CAC'), ('TIN', 'TIN'), ('TCC', 'TCC'), ('ISO_PECB', 'ISO PECB'), ('OTHER', 'Other')], help_text="Type of document (e.g., CAC, TIN, etc. Use 'Other' if not listed)", max_length=50),
        ),
    ]
