# Generated by Django 5.2.2 on 2025-08-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('procurer', 'Procurer'), ('vendor', 'Vendor')], default='vendor', max_length=20),
        ),
    ]
